/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uni.hbarquin.myphotoapp;

import java.awt.Point;

/**
 *
 * @author xavie
 */
public class LinearFitWindow extends javax.swing.JDialog {

    /**
     * Creates new form LinearFitWindow
     */
    public LinearFitWindow(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setTitle("Piecewise linear fit");
        initComponents();
        this.setLocationRelativeTo(null);
        this.closeWindow = true;
    }
    
    public void setClosibleWindowTo(boolean close) {
        this.closeWindow = close;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        inputSections = new javax.swing.JTextArea();
        lblExplication1 = new javax.swing.JLabel();
        lblExplication2 = new javax.swing.JLabel();
        lblSectionByNow = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        inputSections.setColumns(20);
        inputSections.setRows(5);
        inputSections.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputSectionsKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputSectionsKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(inputSections);

        lblExplication1.setText("Choose the sections by typing the points coordinates on each line.");

        lblExplication2.setText("For example: 23 54 13 2 means one section from (23,54) to (13,2).");

        lblSectionByNow.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSectionByNow.setLabelFor(inputSections);
        lblSectionByNow.setText("You have now 0 sections");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(lblExplication1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblExplication2)
                            .addComponent(lblSectionByNow))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(cancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(confirmButton)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblExplication1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExplication2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSectionByNow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(confirmButton))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputSectionsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputSectionsKeyTyped
        //System.out.println("Se ha pulsado una tecla: " + this.inputSections.getText());
    }//GEN-LAST:event_inputSectionsKeyTyped

    private void inputSectionsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputSectionsKeyReleased
        String text = this.inputSections.getText();
        String[] arr = text.split("\n");
        this.lblSectionByNow.setText("You have now " + (text.isEmpty() ? "0" : Integer.toString(arr.length)) + " sections");
    }//GEN-LAST:event_inputSectionsKeyReleased

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        String text = this.inputSections.getText();
        String[] lines = text.split("\n");
        Point[] sections = new Point[lines.length * 2];
        int points_length = 0;
        for (int i = 0; i < lines.length; i++) {
            String[] coordinates = lines[i].split(" ");
            Point p1 = new Point(Integer.parseInt(coordinates[0]), Integer.parseInt(coordinates[1]));
            Point p2 = new Point(Integer.parseInt(coordinates[2]), Integer.parseInt(coordinates[3]));
            sections[points_length++] = p1;
            sections[points_length++] = p2;
        }
        LinearGraphicViewWindow lgvw = new LinearGraphicViewWindow((MainWindow) this.getParent(), rootPaneCheckingEnabled);
        lgvw.setLinearFitWindow(this);
        lgvw.generateGraphicFromCoordinates(sections);
        lgvw.setVisible(true);
        if (this.closeWindow) {
            this.dispose();
        }
    }//GEN-LAST:event_confirmButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LinearFitWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LinearFitWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LinearFitWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LinearFitWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LinearFitWindow dialog = new LinearFitWindow(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private boolean closeWindow;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextArea inputSections;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblExplication1;
    private javax.swing.JLabel lblExplication2;
    private javax.swing.JLabel lblSectionByNow;
    // End of variables declaration//GEN-END:variables
}
